-- ============================================
-- СОЗДАНИЕ СХЕМЫ GOLD
-- ============================================

CREATE SCHEMA IF NOT EXISTS gold;

-- ============================================
-- ИЗМЕРЕНИЕ: dim_date
-- ============================================

CREATE TABLE IF NOT EXISTS gold.dim_date (
    date_key INTEGER PRIMARY KEY,
    full_date DATE NOT NULL,
    day_of_week INTEGER NOT NULL CHECK (day_of_week BETWEEN 1 AND 7),
    week_num INTEGER NOT NULL,
    month_num INTEGER NOT NULL CHECK (month_num BETWEEN 1 AND 12),
    month_name VARCHAR(20) NOT NULL,
    quarter_num INTEGER NOT NULL CHECK (quarter_num BETWEEN 1 AND 4),
    year_num INTEGER NOT NULL,
    is_weekend BOOLEAN NOT NULL DEFAULT FALSE
);

-- ============================================
-- ИЗМЕРЕНИЕ: dim_product
-- ============================================

CREATE TABLE IF NOT EXISTS gold.dim_product (
    product_key INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id INTEGER NOT NULL UNIQUE,
    product_name VARCHAR(200),
    category_id INTEGER,
    category_name VARCHAR(100),
    price NUMERIC(10,2) CHECK (price >= 0),
    class VARCHAR(50),
    resistant BOOLEAN DEFAULT FALSE,
    is_allergic BOOLEAN DEFAULT FALSE,
    vitality_days INTEGER
);

-- ============================================
-- ИЗМЕРЕНИЕ: dim_customer
-- ============================================

CREATE TABLE IF NOT EXISTS gold.dim_customer (
    customer_key INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    customer_id INTEGER NOT NULL UNIQUE,
    first_name VARCHAR(50),
    middle_initial VARCHAR(50),
    last_name VARCHAR(50),
    full_name VARCHAR(200),
    city_id INTEGER,
    address VARCHAR(200)
);

-- ============================================
-- ИЗМЕРЕНИЕ: dim_shop
-- ============================================

CREATE TABLE IF NOT EXISTS gold.dim_shop (
    shop_key INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    shop_id INTEGER NOT NULL UNIQUE,
    shop_address VARCHAR(200),
    city_id INTEGER,
    city_name VARCHAR(100),
    country_id INTEGER,
    country_name VARCHAR(100)
);

-- ============================================
-- ИЗМЕРЕНИЕ: dim_employee (SCD TYPE 2)
-- ============================================

CREATE TABLE IF NOT EXISTS gold.dim_employee (
    employee_key INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    employee_id INTEGER NOT NULL,
    first_name VARCHAR(50),
    middle_initial VARCHAR(50),
    last_name VARCHAR(50),
    full_name VARCHAR(200),
    gender VARCHAR(10),
    birth_date DATE,
    hire_date DATE,
    valid_from_dt DATE NOT NULL DEFAULT '1900-01-01',
    valid_to_dt DATE DEFAULT '9999-12-31',
    is_current BOOLEAN NOT NULL DEFAULT TRUE,
    UNIQUE (employee_id, valid_from_dt)
);

-- ============================================
-- ИЗМЕРЕНИЕ: dim_location
-- ============================================

CREATE TABLE IF NOT EXISTS gold.dim_location (
    location_key INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    city_id INTEGER NOT NULL UNIQUE,
    city_name VARCHAR(100),
    country_id INTEGER,
    country_name VARCHAR(100)
);

-- ============================================
-- ТАБЛИЦА ФАКТОВ: fact_sales
-- ============================================

CREATE TABLE IF NOT EXISTS gold.fact_sales (
    sales_id INTEGER PRIMARY KEY,
    product_key INTEGER NOT NULL REFERENCES gold.dim_product(product_key),
    customer_key INTEGER NOT NULL REFERENCES gold.dim_customer(customer_key),
    shop_key INTEGER NOT NULL REFERENCES gold.dim_shop(shop_key),
    employee_key INTEGER NOT NULL REFERENCES gold.dim_employee(employee_key),
    date_key INTEGER NOT NULL REFERENCES gold.dim_date(date_key),
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    discount_amount NUMERIC(10,2) DEFAULT 0 CHECK (discount_amount >= 0),
    total_price NUMERIC(10,2) NOT NULL CHECK (total_price >= 0),
    net_revenue NUMERIC(10,2) NOT NULL CHECK (net_revenue >= 0)
);

-- ============================================
-- ИНДЕКСЫ ДЛЯ fact_sales
-- ============================================

CREATE INDEX idx_fact_sales_product_key ON gold.fact_sales (product_key);
CREATE INDEX idx_fact_sales_customer_key ON gold.fact_sales (customer_key);
CREATE INDEX idx_fact_sales_shop_key ON gold.fact_sales (shop_key);
CREATE INDEX idx_fact_sales_employee_key ON gold.fact_sales (employee_key);
CREATE INDEX idx_fact_sales_date_key ON gold.fact_sales (date_key);